/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QueueDisplayRouteImport } from './routes/queue-display'
import { Route as PendingApprovalRouteImport } from './routes/pending-approval'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KioskRouteImport } from './routes/kiosk'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperadminTransactionsRouteImport } from './routes/superadmin/transactions'
import { Route as SuperadminStatisticsRouteImport } from './routes/superadmin/statistics'
import { Route as SuperadminSettingsRouteImport } from './routes/superadmin/settings'
import { Route as SuperadminDashboardRouteImport } from './routes/superadmin/dashboard'
import { Route as StaffQueueRouteImport } from './routes/staff/queue'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as SuperadminResidentsIdRouteImport } from './routes/superadmin/residents.$id'
import { Route as StaffProcessRequestIdRouteImport } from './routes/staff/process.$requestId'
import { Route as AdminResidentsIdRouteImport } from './routes/admin/residents.$id'

const QueueDisplayRoute = QueueDisplayRouteImport.update({
  id: '/queue-display',
  path: '/queue-display',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingApprovalRoute = PendingApprovalRouteImport.update({
  id: '/pending-approval',
  path: '/pending-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskRoute = KioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminTransactionsRoute = SuperadminTransactionsRouteImport.update({
  id: '/superadmin/transactions',
  path: '/superadmin/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminStatisticsRoute = SuperadminStatisticsRouteImport.update({
  id: '/superadmin/statistics',
  path: '/superadmin/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminSettingsRoute = SuperadminSettingsRouteImport.update({
  id: '/superadmin/settings',
  path: '/superadmin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminDashboardRoute = SuperadminDashboardRouteImport.update({
  id: '/superadmin/dashboard',
  path: '/superadmin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffQueueRoute = StaffQueueRouteImport.update({
  id: '/staff/queue',
  path: '/staff/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminResidentsIdRoute = SuperadminResidentsIdRouteImport.update({
  id: '/superadmin/residents/$id',
  path: '/superadmin/residents/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffProcessRequestIdRoute = StaffProcessRequestIdRouteImport.update({
  id: '/staff/process/$requestId',
  path: '/staff/process/$requestId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResidentsIdRoute = AdminResidentsIdRouteImport.update({
  id: '/admin/residents/$id',
  path: '/admin/residents/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kiosk': typeof KioskRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/queue-display': typeof QueueDisplayRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/staff/queue': typeof StaffQueueRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
  '/superadmin/settings': typeof SuperadminSettingsRoute
  '/superadmin/statistics': typeof SuperadminStatisticsRoute
  '/superadmin/transactions': typeof SuperadminTransactionsRoute
  '/admin/residents/$id': typeof AdminResidentsIdRoute
  '/staff/process/$requestId': typeof StaffProcessRequestIdRoute
  '/superadmin/residents/$id': typeof SuperadminResidentsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kiosk': typeof KioskRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/queue-display': typeof QueueDisplayRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/staff/queue': typeof StaffQueueRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
  '/superadmin/settings': typeof SuperadminSettingsRoute
  '/superadmin/statistics': typeof SuperadminStatisticsRoute
  '/superadmin/transactions': typeof SuperadminTransactionsRoute
  '/admin/residents/$id': typeof AdminResidentsIdRoute
  '/staff/process/$requestId': typeof StaffProcessRequestIdRoute
  '/superadmin/residents/$id': typeof SuperadminResidentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kiosk': typeof KioskRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/queue-display': typeof QueueDisplayRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/staff/queue': typeof StaffQueueRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
  '/superadmin/settings': typeof SuperadminSettingsRoute
  '/superadmin/statistics': typeof SuperadminStatisticsRoute
  '/superadmin/transactions': typeof SuperadminTransactionsRoute
  '/admin/residents/$id': typeof AdminResidentsIdRoute
  '/staff/process/$requestId': typeof StaffProcessRequestIdRoute
  '/superadmin/residents/$id': typeof SuperadminResidentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kiosk'
    | '/login'
    | '/pending-approval'
    | '/queue-display'
    | '/admin/dashboard'
    | '/staff/queue'
    | '/superadmin/dashboard'
    | '/superadmin/settings'
    | '/superadmin/statistics'
    | '/superadmin/transactions'
    | '/admin/residents/$id'
    | '/staff/process/$requestId'
    | '/superadmin/residents/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kiosk'
    | '/login'
    | '/pending-approval'
    | '/queue-display'
    | '/admin/dashboard'
    | '/staff/queue'
    | '/superadmin/dashboard'
    | '/superadmin/settings'
    | '/superadmin/statistics'
    | '/superadmin/transactions'
    | '/admin/residents/$id'
    | '/staff/process/$requestId'
    | '/superadmin/residents/$id'
  id:
    | '__root__'
    | '/'
    | '/kiosk'
    | '/login'
    | '/pending-approval'
    | '/queue-display'
    | '/admin/dashboard'
    | '/staff/queue'
    | '/superadmin/dashboard'
    | '/superadmin/settings'
    | '/superadmin/statistics'
    | '/superadmin/transactions'
    | '/admin/residents/$id'
    | '/staff/process/$requestId'
    | '/superadmin/residents/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KioskRoute: typeof KioskRoute
  LoginRoute: typeof LoginRoute
  PendingApprovalRoute: typeof PendingApprovalRoute
  QueueDisplayRoute: typeof QueueDisplayRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  StaffQueueRoute: typeof StaffQueueRoute
  SuperadminDashboardRoute: typeof SuperadminDashboardRoute
  SuperadminSettingsRoute: typeof SuperadminSettingsRoute
  SuperadminStatisticsRoute: typeof SuperadminStatisticsRoute
  SuperadminTransactionsRoute: typeof SuperadminTransactionsRoute
  AdminResidentsIdRoute: typeof AdminResidentsIdRoute
  StaffProcessRequestIdRoute: typeof StaffProcessRequestIdRoute
  SuperadminResidentsIdRoute: typeof SuperadminResidentsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/queue-display': {
      id: '/queue-display'
      path: '/queue-display'
      fullPath: '/queue-display'
      preLoaderRoute: typeof QueueDisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-approval': {
      id: '/pending-approval'
      path: '/pending-approval'
      fullPath: '/pending-approval'
      preLoaderRoute: typeof PendingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk': {
      id: '/kiosk'
      path: '/kiosk'
      fullPath: '/kiosk'
      preLoaderRoute: typeof KioskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/transactions': {
      id: '/superadmin/transactions'
      path: '/superadmin/transactions'
      fullPath: '/superadmin/transactions'
      preLoaderRoute: typeof SuperadminTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/statistics': {
      id: '/superadmin/statistics'
      path: '/superadmin/statistics'
      fullPath: '/superadmin/statistics'
      preLoaderRoute: typeof SuperadminStatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/settings': {
      id: '/superadmin/settings'
      path: '/superadmin/settings'
      fullPath: '/superadmin/settings'
      preLoaderRoute: typeof SuperadminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/dashboard': {
      id: '/superadmin/dashboard'
      path: '/superadmin/dashboard'
      fullPath: '/superadmin/dashboard'
      preLoaderRoute: typeof SuperadminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/queue': {
      id: '/staff/queue'
      path: '/staff/queue'
      fullPath: '/staff/queue'
      preLoaderRoute: typeof StaffQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/residents/$id': {
      id: '/superadmin/residents/$id'
      path: '/superadmin/residents/$id'
      fullPath: '/superadmin/residents/$id'
      preLoaderRoute: typeof SuperadminResidentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/process/$requestId': {
      id: '/staff/process/$requestId'
      path: '/staff/process/$requestId'
      fullPath: '/staff/process/$requestId'
      preLoaderRoute: typeof StaffProcessRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/residents/$id': {
      id: '/admin/residents/$id'
      path: '/admin/residents/$id'
      fullPath: '/admin/residents/$id'
      preLoaderRoute: typeof AdminResidentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KioskRoute: KioskRoute,
  LoginRoute: LoginRoute,
  PendingApprovalRoute: PendingApprovalRoute,
  QueueDisplayRoute: QueueDisplayRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  StaffQueueRoute: StaffQueueRoute,
  SuperadminDashboardRoute: SuperadminDashboardRoute,
  SuperadminSettingsRoute: SuperadminSettingsRoute,
  SuperadminStatisticsRoute: SuperadminStatisticsRoute,
  SuperadminTransactionsRoute: SuperadminTransactionsRoute,
  AdminResidentsIdRoute: AdminResidentsIdRoute,
  StaffProcessRequestIdRoute: StaffProcessRequestIdRoute,
  SuperadminResidentsIdRoute: SuperadminResidentsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
